### ISSUE TITLE
Login Nexus API

### ISSUE THREAD

**Issue by vanja-san** [Lake1059/StardewMUI-5#2]
Add a feature to login to nexus api via default browser, the built-in browser is not very workable yet

**Comment by Lake1059** [comment]
The built-in browser of SMU is IE, and it is integrated in .NET, regardless of whether IE is installed in the system. If you are referring to the error that the parameter cannot be obtained, please try to use a VPN or other network acceleration service.

I can't access data from external browsers, all ways of accessing cookies have failed, and the built-in IE browser is the last resort available.

If the web page cannot be displayed normally, please run the registry file in the installation directory, it can force the IE of SMUI to run in IE11 mode. Generally speaking, the installer will automatically install it for you. Without this registry key, IE will run in IE7 mode, and web pages cannot be displayed normally at this time.

**Comment by vanja-san** [comment]
@Lake1059 Is there a guide on how to login? I log in in the built-in browser, but nothing happens in smui (no login)

**Comment by Lake1059** [comment]
here is chs page: https://stardewmui.fandom.com/zh/wiki/%E5%9C%A8%E7%BA%BF%E6%9B%B4%E6%96%B0%E5%8D%95%E4%B8%AA%E9%A1%B9

If you have opened the built-in browser in the settings and logged in, but the webpage still shows that you are not logged in when you open it in the direct update window, please click Login in the webpage again, then close the browser window, and click the file you want to download again. That should fix it.
If you have opened the built-in browser in the settings and logged in, but the webpage still shows that you are not logged in when you open it in the direct update window, please click Login in the webpage again, then close the browser window, and click the file you want to download again. That should fix it.

**Comment by Lake1059** [comment]
Maybe you can record a video and put it on Google Cloud Drive, and then send me the link, maybe I can accurately judge the problem

**Comment by vanja-san** [comment]
@Lake1059 This is what I get every time I click on a long text button:
![изображение](https://user-images.githubusercontent.com/7201687/175326595-e3f75555-b0e8-4bc8-bea5-deecd72e7fd7.png)

**Comment by Lake1059** [comment]
That's right, it's the same effect when you repeatedly visit the login address in an external browser.

**Comment by vanja-san** [comment]
The remote server returned an error: (401)
Unauthorized.

![изображение](https://user-images.githubusercontent.com/7201687/175327875-2d4c527e-3bad-4801-bfb9-b7bb385abeb5.png)

**Comment by Lake1059** [comment]
You forgot to fill in your account API key?

**Comment by Lake1059** [comment]
![image](https://user-images.githubusercontent.com/51054164/175330012-94ae35c7-6aa9-4fc4-aa8a-9e9f7e78fc8f.png)

**Comment by vanja-san** [comment]
@Lake1059 I have difficulty translating from Chinese, so I'm probably missing something, tell me where to find this key!

**Comment by Lake1059** [comment]
here 
![image](https://user-images.githubusercontent.com/51054164/175330546-8b7f93a0-e98a-4a13-a365-e6360a60243e.png)

**Comment by Lake1059** [comment]
https://www.nexusmods.com/users/myaccount?tab=api

**Comment by Lake1059** [comment]
![image](https://user-images.githubusercontent.com/51054164/175330661-0a32388a-1ad7-4d97-bafa-7a27d46c5421.png)

**Comment by vanja-san** [comment]
@Lake1059 thx! I find it!

**Comment by Lake1059** [comment]
Remember: your key must be the same account you log in to in the built-in browser, otherwise there will be an error.

**Comment by vanja-san** [comment]
@Lake1059 OK!

**Comment by Lake1059** [comment]
Also, I have seen the russian language file you made, it works fine, but some width values need to be adjusted, you can publish it on NEXUS so you can update it better. Thank you very much for your work.
